### ISSUE TITLE
SSO unauthorized token with graph toolkit

### ISSUE THREAD

**Issue by ahmedmahmoudR** [mmsharepoint/tab-mgt-person#1]
Hello,

I faced  issue to run the app I want to Use Message extensions with garph toolkit api 
I follow the instructions on this repo 

![This is an image](https://i.imgur.com/wYLrYat.png)

**Comment by mmsharepoint** [comment]
The only direction I can give you with this small amount of information:
Guess you are using people picker?
Did you check which kind of permissions you need? Guess something like User.Read(Basic).All or even Directory.Read.All but I'd check MGT documentation.
If you have that permit AND consent those permissions.
Hope this brings you forward
Markus

**Comment by ahmedmahmoudR** [comment]
I Tried same repo code  Tabb sso without any changes but I faced same issue 
I checked App API permission but its not solved my issue

**Comment by mmsharepoint** [comment]
Then please check latest MGT documentation for any changes

**Comment by mmsharepoint** [comment]
I was checking my sample once again and it perfectly works after I changed the permission to User.ReadBasic.All
Seems there was a change for handling user photos
